import Script from "next/script";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        {/* <Script
          id="ad-script-config"
          strategy="lazyOnload"
          dangerouslySetInnerHTML={{
            __html: `
            atOptions = {
              'key' : 'd090ab5975abd6e2061e3323ef8c1708',
              'format' : 'iframe',
              'height' : 250,
              'width' : 300,
              'params' : {}
            };
          `,
          }}
        />
        <Script
          src="//electricalglimmerexasperate.com/d090ab5975abd6e2061e3323ef8c1708/invoke.js"
          strategy="lazyOnload"
          data-cfasync="false"
          async
        />

        <Script
          id="ad-script-2"
          strategy="lazyOnload"
          dangerouslySetInnerHTML={{
            __html: `
            atOptions = {
              'key' : '9d6e4edb84ce69de668bd394b5e71537',
              'format' : 'iframe',
              'height' : 300,
              'width' : 160,
              'params' : {}
            };
          `,
          }}
        />
        <Script
          src="//electricalglimmerexasperate.com/9d6e4edb84ce69de668bd394b5e71537/invoke.js"
          strategy="lazyOnload"
          data-cfasync="false"
          async
        /> */}
      </head>
      <body>{children}</body>
    </html>
  );
}
